-- Clear old map data
DELETE FROM trip_map_destinations WHERE trip_key = 'jessie-amor-malaysia-singapore';

-- Insert new map destinations matching the updated itinerary
INSERT INTO trip_map_destinations (id, trip_key, day, name, lat, lng, time, notes) VALUES
('day11-flight-mnl', 'jessie-amor-malaysia-singapore', 11, 'Flight to Manila', 14.5086, 121.0198, '11:55 AM', 'Depart for Manila.'),
('day11-flight-kl', 'jessie-amor-malaysia-singapore', 11, 'Flight to Kuala Lumpur', 2.7456, 101.7072, '8:05 PM', 'Depart Manila, arrive KLIA at 12:10 AM July 12.'),
('day12-brunch', 'jessie-amor-malaysia-singapore', 12, 'Late Morning Brunch in Chinatown', 3.1418, 101.6972, '9:30 AM', 'Wake up refreshed, step out of Travelodge, and head straight to a nearby aesthetic cafe or heritage coffee shop around Jalan Sultan for a hearty brunch and a cold iced drink.'),
('day12-kwai-chai-hong', 'jessie-amor-malaysia-singapore', 12, 'Kwai Chai Hong Hidden Lanes', 3.1429, 101.6983, '10:45 AM', 'Wander the beautifully restored brick alleyways right behind Petaling Street.'),
('day12-petaling', 'jessie-amor-malaysia-singapore', 12, 'Jalan Petaling Street Walk', 3.1436, 101.6981, '12:00 PM', 'Stroll through the high-energy stalls under the green canopy roof.'),
('day12-rexkl', 'jessie-amor-malaysia-singapore', 12, 'REXKL BookXcess Maze', 3.1439, 101.6988, '1:00 PM', 'Step into the raw, industrial layout of REXKL to explore the towering multi-level maze of bookshelves.'),
('day12-central-market', 'jessie-amor-malaysia-singapore', 12, 'Central Market & Kasturi Walk', 3.1451, 101.6953, '2:00 PM', 'Kasturi Walk and Central Market artisanal booths and boutique souvenir shops.'),
('day12-merdeka', 'jessie-amor-malaysia-singapore', 12, 'Merdeka Square & River of Life', 3.1485, 101.6944, '3:00 PM', 'Admire the copper domes of Sultan Abdul Samad Building and the Jamek Mosque riverbank.'),
('day12-transit-towers', 'jessie-amor-malaysia-singapore', 12, 'Transit to the Towers', 3.1319, 101.6957, '4:00 PM', 'Drop bags at Travelodge; walk into Pasar Seni LRT Station. Kelana Jaya Line 4 stops to KLCC.'),
('day12-twin-towers', 'jessie-amor-malaysia-singapore', 12, 'Petronas Twin Towers Indoor Tour', 3.1578, 101.7119, '4:30 PM', 'SkyBridge and 86th Floor Observation Deck -- clear afternoon light transitioning to golden hour.'),
('day12-klcc-park', 'jessie-amor-malaysia-singapore', 12, 'KLCC Park & The Transition to Night', 3.1556, 101.7115, '6:15 PM', 'Walk KLCC Park footpaths. Lake Symphony fountain show at 07:30 PM.'),
('day12-transit-back', 'jessie-amor-malaysia-singapore', 12, 'Transit back to Chinatown', 3.1575, 101.7119, '7:45 PM', 'Direct Kelana Jaya Line 4 stops from KLCC to Pasar Seni.'),
('day12-dinner', 'jessie-amor-malaysia-singapore', 12, 'Relaxed Dinner', 3.1418, 101.6972, '8:15 PM', 'Local dinner in Chinatown to celebrate a perfect first day.'),
('day13-breakfast', 'jessie-amor-malaysia-singapore', 13, 'Light breakfast', 3.1432, 101.6983, '5:30 AM', 'Restoran Yusoof Dan Zakhir. Quick Roti Canai and Teh Tarik to fuel up.'),
('day13-walk-pasar-seni', 'jessie-amor-malaysia-singapore', 13, 'Walk to Pasar Seni LRT Station', 3.1319, 101.6957, '5:50 AM', 'Kelana Jaya Line 1 stop to KL Sentral (approx. 3 minutes).'),
('day13-transfer-ktm', 'jessie-amor-malaysia-singapore', 13, 'Transfer to KTM Komuter', 3.1344, 101.6865, '6:00 AM', 'Follow blue signs to KTM Komuter departure gates. Buy cash token or tap Touch n Go.'),
('day13-board-train', 'jessie-amor-malaysia-singapore', 13, 'Board the Train', 3.1344, 101.6865, '6:15 AM', 'Walk down to platform. Look for Ladies-Only coaches (pink stickers).'),
('day13-catch-train', 'jessie-amor-malaysia-singapore', 13, 'Catch the early train', 3.1344, 101.6865, '6:25 AM', 'KTM Komuter. Direct 32-minute journey through northern suburbs.'),
('day13-arrive-batu', 'jessie-amor-malaysia-singapore', 13, 'Arrive at Batu Caves', 3.2379, 101.684, '7:00 AM', 'Temple gates and giant golden statue 2-minute walk from station exit. Climb 272 colorful steps.'),
('day13-genting', 'jessie-amor-malaysia-singapore', 13, 'Go to Genting Island', 3.4338, 101.7934, '8:30 AM', 'Option A: Grab to Awana SkyCentral. Option B: Grab to Gombak LRT + express bus up the mountain.'),
('day13-cable-car', 'jessie-amor-malaysia-singapore', 13, 'Cable Car & Misty Mountain Temple', 3.4237, 101.7785, '9:30 AM', 'Awana SkyWay cable car. Midway stop at Chin Swee Caves Temple and 9-story pagoda.'),
('day13-peak', 'jessie-amor-malaysia-singapore', 13, 'Peak Exploration & SkyAvenue Lunch', 3.4217, 101.7939, '11:00 AM', 'SkyAvenue Mall, Skytropolis, Genting Premium Outlets. Anniversary celebration lunch!'),
('day13-return-kl', 'jessie-amor-malaysia-singapore', 13, 'Return to Kuala Lumpur & Refresh', 3.1432, 101.6983, '4:30 PM', 'Cable car down, express bus or Grab back to Travelodge.'),
('day13-rest', 'jessie-amor-malaysia-singapore', 13, 'Rest', 3.1432, 101.6983, '5:45 PM', 'Rest at Travelodge.'),
('day13-jalan-alor', 'jessie-amor-malaysia-singapore', 13, 'Jalan Alor Night Market', 3.1456, 101.7088, '7:00 PM', 'Grab or MRT to Bukit Bintang. Street seafood, Wong Ah Wah chicken wings, satay, coconut ice cream.'),
('day13-return-mrt', 'jessie-amor-malaysia-singapore', 13, 'Return to Pasar Seni via MRT', 3.1492, 101.7143, '9:00 PM', 'Return via MRT for a deep sleep.'),
('day14-breakfast', 'jessie-amor-malaysia-singapore', 14, 'Quick Morning Breakfast', 3.1432, 101.6983, '6:00 AM', 'Fast, light, cheap near Travelodge / Pasar Seni.'),
('day14-transit-melaka', 'jessie-amor-malaysia-singapore', 14, 'Transit to Melaka', 3.0768, 101.7107, '6:15 AM', 'Rail to TBS, express bus to Melaka (approx. 2 hours).'),
('day14-dutch-square', 'jessie-amor-malaysia-singapore', 14, 'The Historic Red Core & Sultanate Palace', 2.1944, 102.2492, '9:30 AM', 'Dutch Square, St. Pauls Hill, Melaka Sultanate Palace Museum.'),
('day14-jonker-lunch', 'jessie-amor-malaysia-singapore', 14, 'Jonker Street & Peranakan Lunch', 2.195, 102.2475, '11:30 AM', 'Chicken rice balls, Nyonya lunch, Baba & Nyonya Heritage Museum.'),
('day14-maritime-museum', 'jessie-amor-malaysia-singapore', 14, 'Maritime Museum', 2.1896, 102.2479, '1:30 PM', 'Replica of Portuguese ship Flor de la Mar.'),
('day14-river-cruise', 'jessie-amor-malaysia-singapore', 14, 'The Melaka River Cruise', 2.1907, 102.2484, '2:30 PM', '45-minute boat ride past historic bridges, Kampung Morten, street-art murals.'),
('day14-river-walk', 'jessie-amor-malaysia-singapore', 14, 'Riverside Walk & Coffee Break', 2.1919, 102.2491, '3:30 PM', 'Tree-shaded boardwalks. Nyonya Cendol -- shaved ice with palm sugar and coconut milk.'),
('day14-straits-mosque', 'jessie-amor-malaysia-singapore', 14, 'Golden Hour at the Floating Mosque', 2.2054, 102.2365, '5:00 PM', 'Grab to Melaka Straits Mosque. Golden dome over the sea at sunset.'),
('day14-transit-sentral', 'jessie-amor-malaysia-singapore', 14, 'Transit to Melaka Sentral', 2.2509, 102.2861, '5:30 PM', 'Express bus from Melaka Sentral back to TBS, then rail to Pasar Seni.'),
('day14-return-bus', 'jessie-amor-malaysia-singapore', 14, 'Return Bus to Kuala Lumpur', 2.2509, 102.2861, '6:30 PM', 'Smooth air-conditioned ride to TBS terminal, then rail to Pasar Seni.'),
('day14-late-dinner', 'jessie-amor-malaysia-singapore', 14, 'Relaxed Late Dinner', 3.1432, 101.6983, '8:30 PM', 'Late-night dinner near the hotel to unwind.'),
('day14-final-pack', 'jessie-amor-malaysia-singapore', 14, 'Final Pack', 3.1432, 101.6983, '9:00 PM', 'Pack your things, double-check passports, rest before flight to Singapore.'),
('day15-wake-up', 'jessie-amor-malaysia-singapore', 15, 'Wake up', 3.1432, 101.6983, '3:15 AM', 'Wake up, final packing, check passports.'),
('day15-check-out', 'jessie-amor-malaysia-singapore', 15, 'Check out Travelodge', 3.1432, 101.6983, '3:45 AM', 'Check out front desk. Walk to Pasar Seni LRT Station.'),
('day15-grab-klia', 'jessie-amor-malaysia-singapore', 15, 'Transit to KLIA', 2.7456, 101.7072, '4:00 AM', 'Option 1 TRAIN: LRT to KL Sentral then KLIA Ekspres. Option 2 GRAB: direct car to KLIA.'),
('day15-arrive-klia', 'jessie-amor-malaysia-singapore', 15, 'Arrive at KLIA', 2.7456, 101.7072, '6:13 AM', 'Clear airport flow, get ready for Singapore flight.'),
('day15-flight-sg', 'jessie-amor-malaysia-singapore', 15, 'Flight KL to Singapore', 1.3644, 103.9915, '8:00 AM', 'Board flight from KLIA to Changi Airport. Approx. 1 hour.'),
('day15-land-sg', 'jessie-amor-malaysia-singapore', 15, 'Land & Transit to Hotel', 1.3184, 103.8931, '11:00 AM', 'Green East-West Line MRT 6 stops to Paya Lebar. Hotel Classic by Venue drop bags.'),
('day15-geylang-lunch', 'jessie-amor-malaysia-singapore', 15, 'Hawker Lunch at Geylang Serai', 1.3178, 103.8971, '12:15 PM', 'Geylang Serai Market & Food Centre. Nasi Padang or Mee Rebus.'),
('day15-little-india', 'jessie-amor-malaysia-singapore', 15, 'The Vibrant Sights of Little India', 1.306, 103.8498, '1:15 PM', 'MRT to Little India. Sri Veeramakaliamman Temple, House of Tan Teng Niah rainbow villa.'),
('day15-haji-lane', 'jessie-amor-malaysia-singapore', 15, 'Haji Lane & Sultan Mosque', 1.3008, 103.8596, '3:00 PM', 'Kampong Glam. Haji Lane graffiti murals, Bussorah Street photo of Sultan Mosque golden domes.'),
('day15-gardens-bay', 'jessie-amor-malaysia-singapore', 15, 'Gardens by the Bay Outdoor Loop', 1.2816, 103.8636, '5:00 PM', 'Outdoor themed landscapes, dragonfly lake, Supertree Grove -- all free.'),
('day15-garden-rhapsody', 'jessie-amor-malaysia-singapore', 15, 'Garden Rhapsody Light Show', 1.2816, 103.8636, '7:45 PM', 'Benches beneath illuminated Supertrees. Symphony of lights and music.'),
('day15-helix-bridge', 'jessie-amor-malaysia-singapore', 15, 'Helix Bridge to Spectra Light Show', 1.2883, 103.8588, '8:30 PM', 'Cross Helix Bridge to Marina Bay Sands. 09:00 PM Spectra Laser & Water Show.'),
('day15-late-dinner', 'jessie-amor-malaysia-singapore', 15, 'Late Dinner & Return to Hotel', 1.2895, 103.857, '9:15 PM', 'Makansutra Gluttons Bay satay. MRT or Grab to Hotel Classic by Venue.'),
('day16-wake-up', 'jessie-amor-malaysia-singapore', 16, 'Morning Prep Only', 1.314, 103.8976, '5:00 AM', 'Wash up, dress in walking clothes, lace up shoes. Return to pack later.'),
('day16-transit-mrt', 'jessie-amor-malaysia-singapore', 16, 'Early Morning Transit to Downtown', 1.3184, 103.8931, '5:30 AM', 'Paya Lebar MRT. First eastbound green line train 6 stops to Raffles Place.'),
('day16-merlion', 'jessie-amor-malaysia-singapore', 16, 'Merlion Sunrise Experience', 1.2868, 103.8545, '6:00 AM', 'Empty waterfront boardwalk at Merlion Park. Sunrise over Marina Bay Sands -- crowd-free photos.'),
('day16-kaya-breakfast', 'jessie-amor-malaysia-singapore', 16, 'Traditional Kaya Toast Breakfast', 1.2839, 103.8515, '7:15 AM', 'Ya Kun Kaya Toast or Toast Box. Charcoal toast with coconut jam, cold butter, soft-boiled eggs, hot Kopi.'),
('day16-return-hotel', 'jessie-amor-malaysia-singapore', 16, 'Rail Transit Back to Hotel', 1.2839, 103.8515, '8:00 AM', 'Green MRT line from Raffles Place back to Paya Lebar Station.'),
('day16-freshen-up', 'jessie-amor-malaysia-singapore', 16, 'Freshen Up & Pack Things', 1.314, 103.8976, '8:30 AM', 'Shower, change, final sweep for chargers, zip suitcases. Check out front desk, leave bags with concierge.'),
('day16-joo-chiat', 'jessie-amor-malaysia-singapore', 16, 'Joo Chiat Historical Shophouse Roam', 1.3116, 103.9021, '9:30 AM', 'Koon Seng Road pastel shophouses. Joo Chiat Road corner architecture. Kim Choo Kueh Chang Nyonya crafts.'),
('day16-checkout', 'jessie-amor-malaysia-singapore', 16, 'Official Hotel Checkout', 1.314, 103.8976, '11:00 AM', 'Grab suitcases, check out before noon. Leave bags with lobby concierge.'),
('day16-chinatown-sg', 'jessie-amor-malaysia-singapore', 16, 'Chinatown Heritage Murals & Tooth Relic Temple', 1.2834, 103.8437, '11:30 AM', 'Downtown MRT to Chinatown. Buddha Tooth Relic Temple, Sago Street, Mohamed Ali Lane heritage murals. Ice Cream Uncles!'),
('day16-hawker-lunch', 'jessie-amor-malaysia-singapore', 16, 'Pre-Airport Hawker Lunch', 1.2819, 103.8428, '1:00 PM', 'Chinatown Complex Food Centre. Final local meal.'),
('day16-airport-run', 'jessie-amor-malaysia-singapore', 16, 'Collect Suitcases & Airport Run', 1.3644, 103.9915, '2:00 PM', 'MRT to Paya Lebar, collect luggage. Green East-West Line to Changi Airport.'),
('day16-jewel', 'jessie-amor-malaysia-singapore', 16, 'Jewel Changi Rain Vortex Grand Finale', 1.3602, 103.9891, '3:00 PM', 'HSBC Rain Vortex waterfall 7 stories down. Indoor rainforest pathways. Free farewell photos.'),
('day16-departure', 'jessie-amor-malaysia-singapore', 16, 'Flight Check-In & Departure', 1.3644, 103.9915, '4:30 PM', 'Drop bags, clear immigration, stroll to departure gate.');
